version: '2'
services:
 quagga254:
  image: quagga-fpm_test
  container_name: quagga_red13
  stdin_open: true
  tty: true
  privileged: true
  volumes:
    - ~/quagga/volumes/quagga_red13:/etc/quagga
  networks:
   redb:
    ipv4_address: 13.13.13.254
   redc:
    ipv4_address: 172.18.0.2

 quagga10:
  image: quagga-fpm_test
  container_name: quagga_red10
  stdin_open: true
  tty: true
  privileged: true
  volumes:
    - ~/quagga/volumes/quagga_red10:/etc/quagga
  networks:
   redc:
    ipv4_address: 172.18.0.254

 web:
  image: 'gitlab/gitlab-ce:latest'
  container_name: gitlab
  stdin_open: true
  tty: true
  privileged: true
  networks:
   redb:
    ipv4_address: 13.13.13.200
  restart: always
  hostname: 'gitlab.example.com'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://gitlab.example.com:9090'
      gitlab_rails['gitlab_shell_ssh_port'] = 2224
  ports:
    - '9090:9090'
    - '2224:22'
  volumes:
    - '/srv/gitlab/config:/etc/gitlab'
    - '/srv/gitlab/logs:/var/log/gitlab'
    - '/srv/gitlab/data:/var/opt/gitlab'

 host1:
  build: ./hosts
  networks:
   - redb
  container_name: host1
  stdin_open: true
  tty: true
  privileged: true
  entrypoint: /bin/sh

 host2:
  build: ./hosts
  networks:
   - redb
  container_name: host2
  stdin_open: true
  tty: true
  privileged: true
  entrypoint: /bin/sh

 host3:
  build: ./hosts
  networks:
   - redb
  container_name: host3
  stdin_open: true
  tty: true
  privileged: true
  entrypoint: /bin/sh

 dns_server:
  build: ./dns_server
  container_name: master
  volumes:
    - ./dns_server/bind:/etc/bind
  stdin_open: true
  tty: true
  entrypoint: /bin/bash
  networks:
   redb:
    ipv4_address: 13.13.13.51
 
 dhcpd:
  build: ./docker-dhcpd
  container_name: servidor_dhcp
  networks:
   redb:
    ipv4_address: 13.13.13.10
  volumes:
    # Config pass through
    - ~/docker-dhcpd/example/dhcpd.conf:/etc/dhcp/dhcpd.conf
 
 host5:
  build: ./hosts
  networks:
   - redb
  container_name: host5
  stdin_open: true
  tty: true
  privileged: true
  entrypoint: /bin/sh

 host4:
  build: ./hosts
  networks:
   - redb
  container_name: host4
  stdin_open: true
  tty: true
  privileged: true
  entrypoint: /bin/sh

 host6:
  build: ./hosts
  networks:
   redc:
    ipv4_address: 172.18.0.135
  container_name: host6
  stdin_open: true
  tty: true
  privileged: true
  entrypoint: /bin/sh

networks:
  redb:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 13.13.13.0/24

  redc:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.18.0.0/24   
