version: '2'
services:
 quagga254:
  image: quagga-fpm_test
  container_name: quagga254
  stdin_open: true
  tty: true
  privileged: true
  volumes:
    - ~/redes-quagga/volumes/quagga254:/etc/quagga
  networks:
   redb:
    ipv4_address: 13.13.13.254
   redc:
    ipv4_address: 10.10.10.254

 host1:
  build: ./hosts
  networks:
   - redb
  container_name: host1
  stdin_open: true
  tty: true
  privileged: true
  entrypoint: /bin/sh

 host2:
  build: ./hosts
  networks:
   - redb
  container_name: host2
  stdin_open: true
  tty: true
  privileged: true
  entrypoint: /bin/sh

 host3:
  build: ./hosts
  networks:
   - redb
  container_name: host3
  stdin_open: true
  tty: true
  privileged: true
  entrypoint: /bin/sh

 dns_server:
  build: ./dns_server
  container_name: master
  volumes:
    - ./dns_server/bind:/etc/bind
  stdin_open: true
  tty: true
  entrypoint: /bin/bash
  networks:
   redb:
    ipv4_address: 13.13.13.51
 
 dhcpd:
  build: ./docker-dhcpd
  container_name: servidor_dhcp
  networks:
   redb:
    ipv4_address: 13.13.13.10
  volumes:
    # Config pass through
    - ~/docker-dhcpd/example/dhcpd.conf:/etc/dhcp/dhcpd.conf
 
 host5:
  build: ./hosts
  networks:
   - redb
  container_name: host5
  stdin_open: true
  tty: true
  privileged: true
  entrypoint: /bin/sh

 host4:
  build: ./hosts
  networks:
   - redb
  container_name: host4
  stdin_open: true
  tty: true
  privileged: true
  entrypoint: /bin/sh

 host6:
  build: ./hosts
  networks:
   - redb
  container_name: host6
  stdin_open: true
  tty: true
  privileged: true
  entrypoint: /bin/sh

networks:
  redb:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 13.13.13.0/24

  redc:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.10.10.0/24   
