version: '2'
services:
 host1:
  image: busybox
  networks: 
    redb:
     ipv4_address: 13.13.13.11
  container_name: host1
  stdin_open: true
  tty: true
  entrypoint: /bin/sh
  dns: 13.13.13.51

 host3:
  image: busybox
  networks:
   redb:
    ipv4_address: 13.13.13.5
  container_name: host3
  stdin_open: true
  tty: true
  entrypoint: /bin/sh
  dns: 13.13.13.51  

 dns_server:
  build: ./dns_server
  container_name: master
  volumes:
    - ./bind:/etc/bind
  stdin_open: true
  tty: true
  entrypoint: /bin/bash
  networks:
   redb:
    ipv4_address: 13.13.13.51
 
 dhcpd:
  build: ./docker-dhcpd
  container_name: servidor_dhcp
  networks:
   redb:
    ipv4_address: 13.13.13.10
  volumes:
    # Config pass through
    - ~/docker-dhcpd/example/dhcpd.conf:/etc/dhcp/dhcpd.conf
 
 host5:
  image: alpine
  networks:
   - redb
  container_name: host5_dhcp
  stdin_open: true
  tty: true
  privileged: true
  entrypoint: /bin/sh

 host4:
  build: ./hosts
  networks:
   - redb
  container_name: host4
  stdin_open: true
  tty: true
  privileged: true

 host6:
  build: ./hosts
  networks:
   - redb
  container_name: host6
  stdin_open: true
  tty: true
  privileged: true

 quagga254:
  image: quagga-fpm_test
  container_name: quagga254
  stdin_open: true
  tty: true
  privileged: true
  volumes:
    - ~/redes-quagga/volumes/quagga1:/etc/quagga
  networks:
   redb:
    ipv4_address: 13.13.13.25

networks:
  redb:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 13.13.13.0/24   
